### Задание 1  
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

N = 15
a = np.array(sorted(range(N), reverse = True))
a

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### Задание 2  
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [2]:
N = 10
b = np.diag(np.array(sorted(range(N), reverse = True)), k = 0)
print(b)

all_num = b.ravel()
print(f'Сумма по диагонали {np.sum(all_num)}')

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
Сумма по диагонали 45


#### Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [3]:
from numpy import linalg
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

#### Задание 4
В материалах занятия раздел “Задача 4 домашнего задания”
Найдите самого похожего пользователя. 
Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [4]:
user_stats = np.array([
    [2, 1, 0, 0, 0, 0],
    [1, 1, 2, 1, 0, 0],
    [2, 0, 1, 0, 0, 0],
    [1, 1, 2, 1, 0, 1],
    [0, 0, 1, 2, 0, 0],
    [0, 0, 0, 0, 0, 5],
    [1, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 3, 0],
    [1, 0, 0, 2, 1, 4]
])

next_user = np.array([0, 1, 2, 0, 0, 0])
next_user_length = np.linalg.norm(next_user)
all_cosine = []

for i in user_stats:
    user_of_stats_length = np.linalg.norm(i)
    cosine = np.dot(i, next_user) / (next_user_length * user_of_stats_length)
    print(cosine.round(2))
    all_cosine.append(cosine)
    result = all_cosine.index(max(all_cosine)) + 1

print()
print(f'Самый похожий пользователь - {result}')

0.2
0.85
0.4
0.79
0.4
0.0
0.0
0.27
0.0

Самый похожий пользователь - 2
